node {
    tools {
        maven 'Maven 3.3.9'
        jdk 'jdk8'
    }

    stage('Prepare') {
        echo 'Set environment variables and pre-checks'
    }

    stage('Checkout') {
        checkout scm
    }

    stage('Build') {
        echo "M2_HOME = ${M2_HOME}"
        sh "mvn -B -DskipTests clean package"
    }

    stage('Unit Tests') {
        echo "Running Unit tests"
    }

    stage('Integration Test') {
        echo "Define the integration tests"
    }

    stage('SonarQube') {
        echo "Running SonarQube static analyzer..."
    }
}