node {
    stage('Prepare') {
        echo 'Set environment variables and pre-checks'
    }

    stage('Checkout') {
        checkout scm
    }

    stage('Compile'){
        // TODO extract JDK and MAVEN paths to own job <Environment Configuration>
        // Use of Maven
        // --batch-mode : recommended in CI to inform maven to not run in interactive mode (less logs)
        // -V : strongly recommended in CI, will display the JDK and Maven versions in use.
        // -U : force maven to update snapshots each time (default : once an hour, makes no sense in CI).
        // -Dsurefire.useFile=false : useful in CI. Displays test errors in the logs directly (instead of
        //                            having to crawl the workspace files to see the cause).
        withEnv(["JAVA_HOME=${ tool 'jdk-1.8.0_64bits' }", "PATH+MAVEN=${tool 'maven-3.6.1'}/bin:${env.JAVA_HOME}/bin"]) {
            sh "mvn --batch-mode clean install -V -U -Dsurefire.useFile=false"
        }
    }

    stage('Unit Tests') {
        echo "Running Unit tests"
    }

    stage('Integration Test') {
        echo "Define the integration tests"
    }

    stage('SonarQube') {
        echo "Running SonarQube static analyzer..."
    }

    stage('Build') {
       echo "Build package"
    }
}