node {

    agent {
            docker {
                image 'maven:3-alpine'
                args '-v /root/.m2:/root/.m2'
            }
        }

    stage('Prepare') {
        echo 'Something here'
    }

    stage('Checkout') {
        checkout scm
    }

    stage('Build') {
        sh "mvn -B -DskipTests clean package"
    }

    stage('Unit Test') {
        junit '**/target/surefire-reports/TEST-*.xml'
        archive 'target/*.jar'
    }

    stage('Integration Test') {
        echo "integration"
    }

    stage('Connectors Compabibility') {
        echo "Set script here"
    }

    stage('Sonar') {
        echo "integration"
    }
}